#!/usr/bin/env bash

# Titulo: Instalación del gestor de ventanas DWM by Suckless
# Autor: Hector Iván Vega Zamudio
# Correo: mxhectorvega@gmail.com
# Link: https://github.com/mxhectorvega
# Versión:v1.0
# Fecha de actualización 18/06/2022
# Nota: El sistema de preferencia tuvo que haber sido instalado con la herramienta archinstall del liveUSB,
# Seleccionando el perfil Xorg con todos los controladores de código abierto.


clear
printf '\n \nInstalando paquetes necesarios para la config...\n'
sleep 1
clear
sudo pacman -S git make gcc picom nitrogen neofetch network-manager-applet --noconfirm


clear
printf '\n \nClonando repositorios mxhectorvega...\n'
sleep 1
clear
git clone https://github.com/mxhectorvega/suckless "$HOME"/.config/suckless/
git clone https://github.com/mxhectorvega/tipografias
#git clone https://github.com/mxhectorvega/temas

clear
printf '\n \nMoviendo y creando directorios...\n'
sleep 1
clear
mkdir -p "$HOME"/.local/share/fonts/
cp -rf "$HOME"/tipografias/* "$HOME"/.local/share/fonts/
#cp -rf "$HOME"/temas/.{icons,themes}/ "$HOME"
rm -rf "$HOME"/{suckless,tipografias,temas}/

clear
printf '\n \nCompilando codigo fuete Suckless...\n'
sleep 1
clear
cd "$HOME"/.config/suckless/dwm
sudo make install
cd "$HOME"/.config/suckless/st
sudo make install
cd "$HOME"/.config/suckless/slstatus
sudo make install
cd "$HOME"/.config/suckless/dmenu
sudo make install
cd "$HOME"

clear
printf '\n \nCreando entrada para Display Manager...\n'
sleep 1
clear
sudo mkdir /usr/share/xsessions
clear
sudo tee /usr/share/xsessions/dwm.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Dwm
Comment=Dynamic window manager
Exec=dwm
Icon=dwm
Type=XSession
EOF

clear
printf '\n \nCreando .xprofile (cosas que incian con DWM)...\n'
sleep 1
clear
sudo mkdir /usr/share/xsessions
clear
sudo tee $HOME/.xinitrc <<EOF
nm-applet --indicator &
nitrogen --restore &
picom &
slstatus &
exec dwm
EOF

sudo chmod 777 $HOME/.xinitrc

## Instalando repositorio Chaotic para no depender de YAY o PARU.
sleep 1
printf '\n \nInstalando repositorio Chaotic para no depender de YAY o PARU'
clear
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
sudo tee -a /etc/pacman.conf <<EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF
sudo pacman -Sy --noconfirm

clear
printf '\n \n \n \n \n \n \n                                    Configuraciones aplicadas \n \n \n \n \n \n \n \n \n \n'
