#!/bin/bash

clear
printf '\n \nInstalando paquetes necesarios para la config...\n'
sleep 1
clear
sudo pacman -S git make gcc --noconfirm


clear
printf '\n \nClonando repositorios mxhectorvega...\n'
sleep 1
clear
git clone https://github.com/mxhectorvega/suckless "$HOME"/.config/suckless/
#git clone https://github.com/mxhectorvega/tipografias
#git clone https://github.com/mxhectorvega/temas

clear
printf '\n \nMoviendo y creando directorios...\n'
sleep 1
clear
#mkdir -p "$HOME"/.local/share/fonts/
#cp -rf "$HOME"/tipografias/* "$HOME"/.local/share/fonts/
#cp -rf "$HOME"/temas/.{icons,themes}/ "$HOME"
#rm -rf "$HOME"/{suckless,tipografias,temas}/

clear
printf '\n \nCompilando codigo fuete Suckless...\n'
sleep 1
clear
cd "$HOME"/.config/suckless/dwm
sudo make install
cd "$HOME"/.config/suckless/st
sudo make install
cd "$HOME"/.config/suckless/slstatus
sudo make install
cd "$HOME"/.config/suckless/dmenu
sudo make install
cd "$HOME"

clear
printf '\n \nCreando entrada para Display Manager...\n'
sleep 1
clear
sudo mkdir /usr/share/xsessions
clear
sudo tee /usr/share/xsessions/dwm.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Dwm
Comment=Dynamic window manager
Exec=dwm
Icon=dwm
Type=XSession
EOF

clear
printf '\n \nCreando .xprofile (cosas que incian con DWM)...\n'
sleep 1
clear
sudo mkdir /usr/share/xsessions
clear
sudo tee $HOME/.xprofile <<EOF
nm-applet --indicator &
nitrogen --restore &
slstatus &
EOF

sudo chmod 777 $HOME/.xprofile

clear
printf '\n \n \n \n \n \n \n                                    Configuraciones aplicadas \n \n \n \n \n \n \n \n \n \n'
